language: node_js
node_js:
- 12.4.0
cache:
  directories:
  - node_modules
dist: trusty
install:
- npm install
script:
- npm run test
- npm run build
notifications:
  email:
  - ebrehault@gmail.com
deploy:
  provider: releases
  api_key:
    secure: mJQHF3GdCzCFo+2sB6PEtJJjbbleE92fCugN9uIeOynsXYpZ169/2QGhWp0hGpjm3/BNfR07lnHlowCTAorQmsMVdyW6Ud8Ob9g8N45kv35QyibiaO75BBReMuKQbSXx3tfNWrlDcNmpGv/ja0qb4vJEJBL96KjOOEHNA7fdJE88MR35muLZx1GxTkKiAGljhzGHfz/4wFJy3TpVMIB3dQ8vwoWF1Gt8WFAUg8ZxbyWcz4laIKAjZ2F8pdF+dTiRJWEaCiCu8MluCdGHre4LJ4YEAV6P62G8ohN5YKneh+X6OXtGvK497+TA1Hae7xBjzNn3j1ExekUw4aglSj5jTIZ3TA7C5OmBNk23I1aBiHVv2NB+eJNsZVWP0OXxghMkSwPnOIePJr14Que9uA7sYvs5rQ6yuYh7dVMZdxAZAU906HC2J1L/ZXJwDljIg4VXk888dtS/q9ApeR7NJnXXDXkSKmbJEB7D9ftcWlZlnOvqyDKuuKksvCl1k947aBDgvV8A+LNoe1G/wWMTN3/87W4400biLYqPW9hn2G9GVmpyTGqr1atKv+CrPK3NzubBPF96b5CTsG5YOegv1W0eNQ85eVbsHuJvyZQqypN8cohrTEFSSDHpcQ2pYelcWfrA+j8AExB4mUsd/6Bj7oMEBXBVCYdHz5HxqqEiEnDNTQg=
  script: "$TRAVIS_BUILD_DIR/travis_release.sh"
  on:
    repo: guillotinaweb/grange-core
    branch: master
env:
  global:
    secure: XA3j4Q1ZTgmteIfnNRdRvZI4iuNmDgcvmbYzdNcKPVIslFVskZ5dP/t5t+owjR4ARTcEWqcnyryKrKy+J0UUhUMcEvMRSqZnvfKwU3gN0jr0C7tVfLai5NplOlrnyNxqGK6G/XG3riPdzxCnEPkp3WPcimtOoK+QgSucBMZCtN2uIBMqD5KCg+27xeJvGx8U7JYa0sL2GnEvR6Pqsbket71El5vrdx6cGglIPKKwiWTzFDhHkSeTBiQCcfHvkzYxIh9Ur2ObDYAL+oAFNijetmc3dOXNG0eWuZOrrxsqKA23x7ef8InfSoCCwRQOfeTq103sJdv/BI1Yc2624uQDV7INX8u9troNAI8V2Ocm2G4gkN0PHo2zQayIZBXJdWGDpET490NvVPl+DqaU3dDSSzP6V2ALTEngYZR1y1U1iYvsCWD5CoFERQ7Iw3FyKW5rdyFx+JEVP3bLqvvSdO6vW35irAHw7OXwqKotpNIct7B05H4BwPG3qIWZdn201CllYHJ+k/dqTWYRA66Gj/LUIGtd1oAiE+2R+warCiDZ6zAOnPirchcf9GSGLW0AK/WF/l20mcVr43mmDm2DqYhAcpJATmJeqMEBn1jfJB+Rnx6V7kbwqdDpbXP5eQQ7ZGngEyw8qx3RQhGj9QWs+UYNVmnbocQuoukOjtbYooiVUmU=