language: node_js
node_js:
- 12.4.0
cache:
  directories:
  - node_modules
dist: trusty
install:
- npm install
script:
- npm run test
- npm run build
notifications:
  email:
  - ebrehault@gmail.com
deploy:
  provider: releases
  script: "$TRAVIS_BUILD_DIR/travis_release.sh"
  on:
    branch: master
env:
  global:
    secure: XA3j4Q1ZTgmteIfnNRdRvZI4iuNmDgcvmbYzdNcKPVIslFVskZ5dP/t5t+owjR4ARTcEWqcnyryKrKy+J0UUhUMcEvMRSqZnvfKwU3gN0jr0C7tVfLai5NplOlrnyNxqGK6G/XG3riPdzxCnEPkp3WPcimtOoK+QgSucBMZCtN2uIBMqD5KCg+27xeJvGx8U7JYa0sL2GnEvR6Pqsbket71El5vrdx6cGglIPKKwiWTzFDhHkSeTBiQCcfHvkzYxIh9Ur2ObDYAL+oAFNijetmc3dOXNG0eWuZOrrxsqKA23x7ef8InfSoCCwRQOfeTq103sJdv/BI1Yc2624uQDV7INX8u9troNAI8V2Ocm2G4gkN0PHo2zQayIZBXJdWGDpET490NvVPl+DqaU3dDSSzP6V2ALTEngYZR1y1U1iYvsCWD5CoFERQ7Iw3FyKW5rdyFx+JEVP3bLqvvSdO6vW35irAHw7OXwqKotpNIct7B05H4BwPG3qIWZdn201CllYHJ+k/dqTWYRA66Gj/LUIGtd1oAiE+2R+warCiDZ6zAOnPirchcf9GSGLW0AK/WF/l20mcVr43mmDm2DqYhAcpJATmJeqMEBn1jfJB+Rnx6V7kbwqdDpbXP5eQQ7ZGngEyw8qx3RQhGj9QWs+UYNVmnbocQuoukOjtbYooiVUmU=
